### ISSUE TITLE
Density matrices

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#11]
Implement density matrices (1-RDMs and 2-RDMs) as separate classes. Use a 'Builder' for derived classes that implement the formulas for:
- [x] DOCI density matrices: see #43
- [x] FCI density matrices: see #55 
- [x] selected CI density matrices: see #80 

We should also implement functions like
- `OneRDM.trace()`
- `OneRDM.diagonalize()`
- `TwoRDM.contract()`
- `TwoRDM.trace()`

**Comment by lelemmen** [comment]
Further discussions about the implementation of the `RDMBuilder` class is in #60.
