### ISSUE TITLE
CI module improvements

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#604]
**Describe the feature you'd like**
Since the CI module currently has no maintainers, it is very susceptible to acquire technical debt. This issue will gather an overview of issues that should be resolved in order to increase this module's stability.

New functionality
---
- [ ] Implement CI objectives. (#541)
- [ ] Implement CI, CISD, seniority-based truncated CI ONV bases. (#352, #502)
- [ ] Allow 64+ orbital calculations (#71).
- [ ] Implementation of Dyson orbitals and amplitudes (#422)
- [ ] Matrix-vector products for frozen core calculations (#465)
- [ ] Read in GAMESS-US wave functions (#481)

API improvements
---
- [x] Add DM API to LinearExpansion (#531)
- [x] Add Python bindings for CI density matrices. (#606)
- [ ] Implement (diagonally-approximated Hessian) OO-CI (MC-SCF) for all types of CI that can generate 2-DMs. (#440)
- [ ] Add ONVPath API (#661 )

Mathematical optimization
---
- [ ] Improve initial guess for Davidson (#72).
- [ ] Allow different Davidson preconditioners (#432).
- [ ] Rewrite NoPivotLUDecomposition as an Algorithm (#554).
- [ ] Fix benchmark performance (#650).
- [ ] Add ONV manipulation to website (#662 )

Documentation
---
- [ ] Documenting the `HamiltonianBuilder` API;
- [ ] Rename `HamiltonianBuilder` to `HamiltonianMatrixCalculator`
- [ ] Improving the documentation in all files `*/Processing/DensityMatrices/*`.

Legacy code
---
- [ ] Checking all source files for variables/comments like "Fock space", which is old legacy nomenclature and should be replaced
- [ ] Re-enable frozen-core DOCI calculations. (#533) 
- [ ] Re-enable frozen-core DOCI DM calculations. (#530)
- [x] Check if spin-unresolved and spin-resolved calculations are well-separated. (#505) 
- [ ] Remove base and general density-matrix-calculators. (#640)
- [ ] Fix duplicate code in DM calculators. (#236)
- [ ] Rewrite CI density matrix routines (#648)
- [ ] Refactor `EvaluationIterator` (#649)
- [ ] Improve CI codes that are related to the notorious `shiftUntilNextOccupiedOrbital`

**Additional context**
Since @tmhuysen has spent a lot of time developing well-performing source code for CI methods, I don't think we have to rewrite this module altogether. We should be able to understand 100% what is written, document the code accordingly and feature simplifications where possible.

**Comment by lelemmen** [comment]
Closed in favor of maintaining an open-source project board.
