### ISSUE TITLE
Compile-time correctness

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#688]
**Introduction**
One of the defining features of this C++ library is compile-time correctness. In easy words: _what is implemented in the C++ library should be relatable to a specific part of electronic structure theory_. Since we can never aim for "having implemented everything", we cannot use run-time polymorphism using pure virtual methods and overrides, because if only one implementation were missing (like some obscure matrix-vector product that is only used for one of the deriving types), we'd have to throw a runtime error, possibly wasting hours of compute.

This issue will track the progress on implementing this behavior, since I'm not comfortable shipping a v1.0.0 without it.

This is a multi-PR, multi-month (and hopefully, multi-contributor) project. Once it is achieved, we'll be further increasing the gap between other software packages and ours, since the connection between the theory and the code library is further deepened. It won't be long until we have implemented electronic structure's domain specific language.

**When is this issue finished?**
- [x] When all types have been scrutinized for their R/U/G behavior;
- [x] When the CI module implementation no longer uses pure virtual methods;
- [x] When the Python bindings have been adjusted to accommodate all the changes;
~- [ ] When the website's documentation covers all the changes that are related to this issue.~ This is transferred to #607.

**Comment by lelemmen** [comment]
Part 1: Implementing the back bone `SimpleSQOneElectronOperator` for R/G one-electron operators.
--- 

This PR (#686) will gather work on refactoring the code such that it is more compile-time correct. We had been using `SQOneElectronOperator` and `OneDM` to refer to either the restricted or generalized form, but this leads to potentially mixing restricted one-electron operators with generalized density matrices, something our code isn't prepared for. (Note that the theory doesn't disallow this mixing, it just requires a different implementation.)

**Comment by lelemmen** [comment]
Part 2: BasisTransformable and GSQOneElectronOperator
---

In this PR, I've introduced the `BasisTransformable` interface. Unfortunately, `SimpleSQOneElectronOperator` now implements two interfaces, which both inherit from `CRTP`, which causes a diamond pattern and therefore an ambiguous `derived()` method. In order to resolve this issue, I'll opt for removing the `CRTP` as a base class for the interfaces, having to use the appropriate `static_cast<const&>` or `static_cast<&>` wherever needed.

**Comment by lelemmen** [comment]
Part 3: Density matrices
---

There are a couple of things I don't really like about the current density matrices, which are the subject of this PR:
1. Their names start with 'One' and 'Two' instead of '1' and '2'.
1. They're far away in the `/Processing/` directory.
1. `OneDM` inherits from `QCMatrix`, although that type is designed to have APIs related to one-electron transformations.
1. Even though `SpinResolvedOne/TwoDM` is an apt name, it would be more in line with `R/U/GSQOperator` and `R/U/GSpinorBasis` to introduce `R/U/GDM`s.

**Comment by lelemmen** [comment]
Part 4: Transformation matrices
---

The transformation matrices seem to be the types that are the most fundamental in this refactor, so it's imperative to get them 'right' as soon as possible. In this PR, I'm implementing `R/U/GTransformationMatrix`.

**Comment by lelemmen** [comment]
Part 5: Bringing over calculate functions from SQOneElectronOperator
---

We're almost done bringing over `SQOneElectronOperator`'s functionality into `Simple`-, `R`- and `GSQOneElectronOperator`. 🎉 What remains to be done at this moment is to bring the `calculate` and `evaluate` methods.

For the Fockian calculations, I don't really see any issues. However, there's going to be an issue with the functions:
- `calculateDensity`; and
- `evaluate`.

These methods are currently in the code base to support working with [_second-quantized matrix elements of the density operator_](https://gqcg-res.github.io/knowdes/second-quantized-density-and-current-density-operators.html), i.e. Schrödinger distributions. **Eigen is going to complain** that various vector arithmetic operators aren't implemented on `LinearCombination` and `ScalarFunctionProduct`. (The reason why we're seeing this now and didn't in the past is because we're now enforcing conformity to `BasisTransformable` and `JacobiRotatable` and the compiler **has** to instantiate the definitions. We're not removing functionality from `SQOneElectronOperator`, we were just lucky that the compiler never had to instantiate rotation and transformation functionality on the second-quantized density matrix-elements.)

Since the goal of `SimpleSQOneElectronOperator` (and its deriving classes `RSQOneElectronOperator` and `GSQOneElectronOperator`) is to be able to work with one-electron operators (whose matrix elements are scalars -either doubles or complex doubles-), I'm not going to make `SimpleSQOneElectronOperator` less readable by using obscure C++ constructs.

On the contrary: I'm aiming for maintainability, so I'll just make a special type for one-electron operators that **can be evaluated at a point in space**. This type won't conform to `BasisTransformable` or `JacobiRotatable`, but I'll implement `void transform()` and `void rotate()` methods, so that the current functionality that is available on `SQOneElectronOperator` is not lost. In the process, I'll make sure that there is absolutely no 'quick-fix code duplication'.

**Comment by lelemmen** [comment]
Part 6: Phasing out SQOneElectronOperator
---

Since we're finished with appropriately implementing `SQOneElectronOperator`'s methods onto `SimpleSQOneElectronOperator`, `SQOneElectronOperator` may start to be phased out!

**Comment by lelemmen** [comment]
Part 6.1: Compile-time correct density matrices
---

The problem with #701 is that it is becoming too large. Therefore, I've split up some of the work in separate PRs. I'll first tackle compile-time correct density matrices.

**Comment by lelemmen** [comment]
Part 6.2: part 6 in disguise
---

I've restarted work on phasing out `SQOneElectronOperator`. I really want to continue the workflow, so I'm inclined not to split up this PR any further. I'll document changes in this comment.

**Comment by lelemmen** [comment]
Part 7 - Fixing the frenzy - R/U/G/ SQOperators
---

#701 was a real pain (as you can see from the number of lines of code that were changed). A lot of code was disabled, but since the code compiles and the tests (those that aren't disabled) work. Now we can gradually start reintroducing the behavior.

This PR will entail the following work on R/U/G operators:
- [ ] Writing tests for the 'simple' SQ operators;
- [ ] Rewriting `USQOneElectronOperator`, `USQTwoElectronOperator` and `USQHamiltonian`;
- [ ] Scrutinizing R/U/GHF to work with the R/U/G types.

Afterwards, I'll start removing some classes:
- [ ] The old `SQOneElectronOperator` and `SQTwoElectronOperator`;
- [ ] The old classes `QCMatrix` and `QCRankFourTensor`;
